#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.local/bin/env
$HOME/.config/polybar/launch.sh
feh --bg-scale $HOME/Media/pics/dwall.png --no-fehbg
picom --experimental-backends -b

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
