; file:   ~/.config/polybar/config
; author: vanir

[colors]
background = #292d3e
background-alt = #676e95
foreground = #959dcb
foreground-alt = #959dcb
primary = #292d3e
secondary =  #ffcb6b
alert = #f07178

[bar/vanir]
monitor = ${env:MONITOR:}
width = 100%
height = 32

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3 
line-color = ${colors.primary}

border-size = 0 
border-color = ${colors.primary} 

padding-left = 0
padding-right = 0

bottom = false

font-0 = FontAwesome5Free:style=Solid:pixelsize=14;2
font-1 = FontAwesome5Brands:style=Solid:pixelsize=14;2
font-2 = FiraCodeRetina:style=Solid:pixelsize=12;2

modules-left = menu i3
modules-right = eth alsa date powermenu

tray-position = right
tray-padding = 2

cursor-click = pointer
enable-ipc = true

cursor-scroll = ns-resize

[bar/bottom]
monitor = ${env:MONITOR:}
width = 100%
height = 24
bottom = true
padding-right = 1
fixed-center =false
line-size = 2
module-margin-right = 1
font-0 = FontAwesome5Free:style=Solid:pixelsize=14;2
font-1 = FontAwesome5Brands:style=Solid:pixelsize=14;2
font-2 = FiraCodeRetina:style=Solid:pixelsize=12;2
enable-ipc = true
modules-right = cpu temp temp2 temp3 temp4
background = ${colors.background}
foreground = ${colors.foreground}

[module/menu]
type = custom/text
content = 
content-padding = 1
content-foreground = ${colors.primary}
content-background = ${colors.secondary}
click-left = exec rofi -show drun -display-drun "Applications" -hide-scrollbar true -bw 0 -lines 10 -line-padding 10 -width 30 -xoffset 0 -yoffset 35 -location 1 -columns 2 -show-icons -icon-theme "Papirus" -font "Fire Code Retina 14" -color-enabled true -color-window "#1c1f2b, #1c1f2b, #1c1f2b" -color-normal "#292d3e, #959dcb, #292d3e, #ffcb6b, #292d3e" -color-active "#222222, #b1b4b3, #222222, #007763, #b1b4b3" -color-urgent "#222222, #b1b4b3, #222222, #77003d, #b1b4b3"

[module/i3]
type = internal/i3
pin-workspaces = true
enable-click = true
fuzzy-match = true
enable-scroll = false
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-foreground = ${colors.secondary}
label-focused-background = ${colors.background-alt}
label-focused-underline=   ${colors.secondary}
label-focused-padding = 1.5

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 1

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-foreground = ${colors.secondary}
label-visible-background = ${self.label-focused-background}
label-visible-underline =  ${self.label-focused-underline}
label-visible-padding =    ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

[module/eth]
type = internal/network
interface = enp3s0
interval = 1

format = <label>

label-connected = 
format-connected-padding = 1
format-connected-background = #ffeac3
format-connected-foreground = ${colors.primary}

[module/date]
type = internal/date
interval = 1.0

format = <label>

format-background = #ffd588
format-foreground = ${colors.primary}
format-padding = 1

date = " %b %d"

time = %H:%M

label =%date% %time%



[module/alsa]
type = internal/alsa

format-volume = <ramp-volume> <label-volume>
format-volume-background = #ffdfa6
format-volume-padding = 1

label-volume = %percentage%
label-volume-foreground = ${colors.primary}

label-muted = 
format-muted-foreground = ${colors.primary}
format-muted-background = #ffdfa6
format-muted-padding = 1

ramp-volume-0 = 
ramp-volume-foreground =  ${colors.primary}

[module/cpu]
type = internal/cpu
interval = 0.5

format = <label> <ramp-coreload>

label = 

ramp-coreload-spacing = 1
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █

[module/temp]
type = internal/temperature
interval = 0.5
thermal-zone = 0
;warn-temperature = 60

hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp2_input
base-temperature = 20
warn-temperature = 60

format = <ramp> <label>
format-warn = <ramp> <label-warn>

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 =  
ramp-foreground = ${colors.foreground-alt}

[module/temp2]
type = internal/temperature
interval = 0.5
thermal-zone = 0
;warn-temperature = 60

hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp3_input
base-temperature = 20
warn-temperature = 60

format = <label>
format-warn = <label-warn>

label = %temperature-c% 
label-warn = %temperature-c% 
label-warn-foreground = ${colors.secondary}

[module/temp3]
type = internal/temperature
interval = 0.5
thermal-zone = 0
;warn-temperature = 60

hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp4_input
base-temperature = 20
warn-temperature = 60

format = <label>
format-warn = <label-warn>

label = %temperature-c% 
label-warn = %temperature-c% 
label-warn-foreground = ${colors.secondary}

[module/temp4]
type = internal/temperature
interval = 0.5
thermal-zone = 0
;warn-temperature = 60

hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp5_input
base-temperature = 20
warn-temperature = 60

format = <label>
format-warn = <label-warn>

label = %temperature-c% 
label-warn = %temperature-c% 
label-warn-foreground = ${colors.secondary}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 0

label-open =  
label-open-foreground = ${colors.primary}
label-open-background = ${colors.secondary}
label-open-padding = 1

label-close =  
label-close-foreground = ${colors.primary}
label-close-background = ${colors.secondary}
label-close-padding = 1

menu-0-1 = REBOOT| 
menu-0-1-exec = menu-open-1
menu-0-0 = LOGOUT|
;menu-0-0-exec = qdbus org.kde.ksmserver /KSMServer org.kde.KSMServerInterface.logout -1 -1 -1
menu-0-0-exec = menu-open-3
menu-0-2 = POWER
menu-0-2-exec = menu-open-2

menu-1-0 = NO|
menu-1-0-exec = menu-open-0
menu-1-1 = YES
menu-1-1-exec = reboot

menu-2-0 = NO|
menu-2-0-exec = menu-open-0
menu-2-1 = YES
menu-2-1-exec = poweroff

menu-3-0 = NO|
menu-3-0-exec = menu-open-0
menu-3-1 = YES
menu-3-1-exec = i3-msg exit

[settings]
screenchange-reload = true

[global/wm]
margin-top = 5
margin-bottom = 5